# Generated by Django 4.2.2 on 2024-11-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='main/doctor/avatar/', verbose_name='Аватар'),
        ),
    ]
